### ISSUE TITLE
Cannot deploy bundle for charmed kubernetes 942

### ISSUE THREAD

**Issue by FrancescoDeSimone** [charmed-kubernetes/cdk-shrinkwrap#31]
### Description

cannot deploy bundle generated from  charmed-kubernetes-942.  

```  
ERROR cannot deploy bundle: the provided bundle has the following errors:  
resource revision "kubernetes-worker" is not int or string  
resource revision "kubernetes-worker" is not int or string  
resource revision "kubernetes-worker" is not int or string  
resource revision "kubernetes-worker" is not int or string
```

The error seems linked to an error in the bundle resources
```
  kubernetes-worker:
    annotations:
      gui-x: '90'
      gui-y: '850'
    channel: 1.23/edge
    charm: ./charms/kubernetes-worker/1.23/edge
    constraints: cores=4 mem=4G root-disk=16G
    expose: true
    num_units: 3
    options:
      channel: 1.23/stable
    resources:
      cni-amd64: ./resources/kubernetes-worker/cni-amd64/cni.tgz
      cni-arm64: ./resources/kubernetes-worker/cni-arm64/cni.tgz
      cni-s390x: ./resources/kubernetes-worker/cni-s390x/cni.tgz
      core:
        description: 'core snap

          [DEPRECATED] in favor of using a Snap Store Proxy.

          See https://ubuntu.com/kubernetes/docs/proxies for more details.

          '
        filename: core.snap
        type: file
      kube-proxy:
        description: 'kube-proxy snap

          [DEPRECATED] in favor of using a Snap Store Proxy.

          See https://ubuntu.com/kubernetes/docs/proxies for more details.

          '
        filename: kube-proxy.snap
        type: file
      kubectl:
        description: 'kubectl snap

          [DEPRECATED] in favor of using a Snap Store Proxy.

          See https://ubuntu.com/kubernetes/docs/proxies for more details.

          '
        filename: kubectl.snap
        type: file
      kubelet:
        description: 'kubelet snap

          [DEPRECATED] in favor of using a Snap Store Proxy.

          See https://ubuntu.com/kubernetes/docs/proxies for more details.

          '
        filename: kubelet.snap
        type: file
```

but even after a manual correction I still get
```
ERROR cannot deploy bundle: unexpected charm "containerd", charm not found for application "containerd"
```

### Step to reproduce
```
./shrinkwrap-lxc.sh charmed-kubernetes-942
cd build
tar xf cs:charmed-kubernetes-942* --force-local
cd cs:charmed-kubernetes-942*
juju deploy  ./bundle.yaml
```
